/*
 *--------------------------------------------------------
 * Administrateur
 *--------------------------------------------------------
 * Project     : fuzzBuzz
 *
 * Copyright Administrateur,  All Rights Reserved.
 *
 * This software is the confidential and proprietary
 * information of Administrateur.
 * You shall not disclose such Confidential Information
 * and shall use it only in accordance with the terms
 * of the license agreement you entered into with
 * Administrateur.
 *-------------------------------------------------------- 
 * 
 * Fichier 		:	FuzzBuzz.java
 * Cree le 		: 	3 sept. 2016 à 16:17:52
 * Auteur		: 	mmenhour
 * 
 * Description 	:
 * 
 *---------------------------------------------------------
 */

package com.org.fuzz;

/**
 * A Renseigner.
 * @author  : admin
 * @project : fuzzBuzz
 * @package : com.org
 * @date    : 3 sept. 2016 16:17:52
 */
public interface FuzzBuzz
{
   /**
    * 
    * @param value : int
    * @return : String 
    * @throws IllegalArgumentException :  Propagates the exception generated by the program
    */
   String fuzzBuzz( int value ) throws IllegalArgumentException;
}
